services:
  - type: web
    name: iwms-server
    env: node
    region: oregon
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://obiriisaac116_db_user:fX6n8YhminCE8Uq1@cluster0.8c87k8n.mongodb.net/iwms?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_ORIGIN
        value: https://iwms-p1ru.onrender.com
